// <auto-generated />
using System;
using BlackJack.PL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlackJack.PL.Migrations
{
    [DbContext(typeof(BlackJackEntities))]
    partial class BlackJackEntitiesModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlackJack.PL.Entities.tblCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CardIMG")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DeckId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Suit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeckId");

                    b.ToTable("tblCards");

                    b.HasData(
                        new
                        {
                            Id = new Guid("588aacd0-92f3-4526-9526-9e1a91fffed1"),
                            CardIMG = "",
                            DeckId = new Guid("e01c46df-21e8-4ea4-9697-731b428dee4a"),
                            Rank = "Ace",
                            Suit = "Hearts",
                            Value = 1
                        },
                        new
                        {
                            Id = new Guid("b7545976-cd05-44a1-bbac-b9cf9e30d432"),
                            CardIMG = "",
                            DeckId = new Guid("e01c46df-21e8-4ea4-9697-731b428dee4a"),
                            Rank = "2",
                            Suit = "Hearts",
                            Value = 2
                        },
                        new
                        {
                            Id = new Guid("7fcff96d-8ebb-4e88-99c9-99e1fe4d2eaa"),
                            CardIMG = "",
                            DeckId = new Guid("e01c46df-21e8-4ea4-9697-731b428dee4a"),
                            Rank = "3",
                            Suit = "Hearts",
                            Value = 3
                        },
                        new
                        {
                            Id = new Guid("ef3399e1-5134-46e2-9de4-c39a0a3126e0"),
                            CardIMG = "",
                            DeckId = new Guid("e01c46df-21e8-4ea4-9697-731b428dee4a"),
                            Rank = "4",
                            Suit = "Hearts",
                            Value = 4
                        },
                        new
                        {
                            Id = new Guid("1ab1a9cd-b681-4858-a0b1-2d650e7f12af"),
                            CardIMG = "",
                            DeckId = new Guid("e01c46df-21e8-4ea4-9697-731b428dee4a"),
                            Rank = "5",
                            Suit = "Hearts",
                            Value = 5
                        },
                        new
                        {
                            Id = new Guid("6dd04525-81fa-42da-a3d8-275c3968b8c6"),
                            CardIMG = "",
                            DeckId = new Guid("e01c46df-21e8-4ea4-9697-731b428dee4a"),
                            Rank = "6",
                            Suit = "Hearts",
                            Value = 6
                        },
                        new
                        {
                            Id = new Guid("9f7ae0a1-a579-46bb-8cf5-b3a998a4837c"),
                            CardIMG = "",
                            DeckId = new Guid("e01c46df-21e8-4ea4-9697-731b428dee4a"),
                            Rank = "7",
                            Suit = "Hearts",
                            Value = 7
                        },
                        new
                        {
                            Id = new Guid("1839df52-d8c8-4fd0-af7f-2fbe28d6344c"),
                            CardIMG = "",
                            DeckId = new Guid("e01c46df-21e8-4ea4-9697-731b428dee4a"),
                            Rank = "8",
                            Suit = "Hearts",
                            Value = 8
                        },
                        new
                        {
                            Id = new Guid("97d37fcf-d878-49f1-a73f-4353ba1ddd0b"),
                            CardIMG = "",
                            DeckId = new Guid("e01c46df-21e8-4ea4-9697-731b428dee4a"),
                            Rank = "9",
                            Suit = "Hearts",
                            Value = 9
                        },
                        new
                        {
                            Id = new Guid("0e37772a-04e6-46c1-ad5e-07a3f21a7348"),
                            CardIMG = "",
                            DeckId = new Guid("e01c46df-21e8-4ea4-9697-731b428dee4a"),
                            Rank = "10",
                            Suit = "Hearts",
                            Value = 10
                        },
                        new
                        {
                            Id = new Guid("9247de9b-d202-4a9b-a99d-df091624988a"),
                            CardIMG = "",
                            DeckId = new Guid("e01c46df-21e8-4ea4-9697-731b428dee4a"),
                            Rank = "Jack",
                            Suit = "Hearts",
                            Value = 10
                        },
                        new
                        {
                            Id = new Guid("a4c591f4-6fee-4d9e-9d87-53871b15482a"),
                            CardIMG = "",
                            DeckId = new Guid("e01c46df-21e8-4ea4-9697-731b428dee4a"),
                            Rank = "Queen",
                            Suit = "Hearts",
                            Value = 10
                        },
                        new
                        {
                            Id = new Guid("aebce7a5-1010-4b1a-89d0-92ea5221cf3a"),
                            CardIMG = "",
                            DeckId = new Guid("e01c46df-21e8-4ea4-9697-731b428dee4a"),
                            Rank = "King",
                            Suit = "Hearts",
                            Value = 10
                        },
                        new
                        {
                            Id = new Guid("1edf077b-b2c7-4215-93e8-cd8f09abbffd"),
                            CardIMG = "",
                            DeckId = new Guid("e01c46df-21e8-4ea4-9697-731b428dee4a"),
                            Rank = "Ace",
                            Suit = "Spades",
                            Value = 1
                        },
                        new
                        {
                            Id = new Guid("59dd4ba0-475d-4bb6-93e9-cd1472417539"),
                            CardIMG = "",
                            DeckId = new Guid("e01c46df-21e8-4ea4-9697-731b428dee4a"),
                            Rank = "2",
                            Suit = "Spades",
                            Value = 2
                        },
                        new
                        {
                            Id = new Guid("340b85e5-61b8-4478-b5ce-61c0bae38161"),
                            CardIMG = "",
                            DeckId = new Guid("e01c46df-21e8-4ea4-9697-731b428dee4a"),
                            Rank = "3",
                            Suit = "Spades",
                            Value = 3
                        },
                        new
                        {
                            Id = new Guid("f5bb7f8c-f5db-4d0c-8239-855914107599"),
                            CardIMG = "",
                            DeckId = new Guid("e01c46df-21e8-4ea4-9697-731b428dee4a"),
                            Rank = "4",
                            Suit = "Spades",
                            Value = 4
                        },
                        new
                        {
                            Id = new Guid("59a01960-ab43-463d-b8d8-ac7efc93cc56"),
                            CardIMG = "",
                            DeckId = new Guid("e01c46df-21e8-4ea4-9697-731b428dee4a"),
                            Rank = "5",
                            Suit = "Spades",
                            Value = 5
                        },
                        new
                        {
                            Id = new Guid("e3d2a657-5758-4933-8cd0-5e6b19c6b0f1"),
                            CardIMG = "",
                            DeckId = new Guid("e01c46df-21e8-4ea4-9697-731b428dee4a"),
                            Rank = "6",
                            Suit = "Spades",
                            Value = 6
                        },
                        new
                        {
                            Id = new Guid("c73c3c01-f3f5-427b-b1ef-44eaee24a8a3"),
                            CardIMG = "",
                            DeckId = new Guid("e01c46df-21e8-4ea4-9697-731b428dee4a"),
                            Rank = "7",
                            Suit = "Spades",
                            Value = 7
                        },
                        new
                        {
                            Id = new Guid("a229bf64-3f3e-4d13-bf26-40822c137619"),
                            CardIMG = "",
                            DeckId = new Guid("e01c46df-21e8-4ea4-9697-731b428dee4a"),
                            Rank = "8",
                            Suit = "Spades",
                            Value = 8
                        },
                        new
                        {
                            Id = new Guid("fc50fc01-91cf-4d71-9d20-1db664fa0bd7"),
                            CardIMG = "",
                            DeckId = new Guid("e01c46df-21e8-4ea4-9697-731b428dee4a"),
                            Rank = "9",
                            Suit = "Spades",
                            Value = 9
                        },
                        new
                        {
                            Id = new Guid("acf0f456-a63d-4220-b6c7-28c4c9110abb"),
                            CardIMG = "",
                            DeckId = new Guid("e01c46df-21e8-4ea4-9697-731b428dee4a"),
                            Rank = "10",
                            Suit = "Spades",
                            Value = 10
                        },
                        new
                        {
                            Id = new Guid("105af2a9-c9e5-41a4-8b8b-2b20626eac76"),
                            CardIMG = "",
                            DeckId = new Guid("e01c46df-21e8-4ea4-9697-731b428dee4a"),
                            Rank = "Jack",
                            Suit = "Spades",
                            Value = 10
                        },
                        new
                        {
                            Id = new Guid("deee770f-a15c-465b-ab13-c2321493f7da"),
                            CardIMG = "",
                            DeckId = new Guid("e01c46df-21e8-4ea4-9697-731b428dee4a"),
                            Rank = "Queen",
                            Suit = "Spades",
                            Value = 10
                        },
                        new
                        {
                            Id = new Guid("80f8b185-b671-4c68-a87d-a99f443ad3eb"),
                            CardIMG = "",
                            DeckId = new Guid("e01c46df-21e8-4ea4-9697-731b428dee4a"),
                            Rank = "King",
                            Suit = "Spades",
                            Value = 10
                        },
                        new
                        {
                            Id = new Guid("73af6a8a-37f1-4033-8c4a-8e349d6c3bdd"),
                            CardIMG = "",
                            DeckId = new Guid("e01c46df-21e8-4ea4-9697-731b428dee4a"),
                            Rank = "Ace",
                            Suit = "Diamonds",
                            Value = 1
                        },
                        new
                        {
                            Id = new Guid("39825b57-d33a-4dde-b7a0-1f0e33a60b4d"),
                            CardIMG = "",
                            DeckId = new Guid("e01c46df-21e8-4ea4-9697-731b428dee4a"),
                            Rank = "2",
                            Suit = "Diamonds",
                            Value = 2
                        },
                        new
                        {
                            Id = new Guid("36fcba80-f81b-4638-b6d8-f5454024eddc"),
                            CardIMG = "",
                            DeckId = new Guid("e01c46df-21e8-4ea4-9697-731b428dee4a"),
                            Rank = "3",
                            Suit = "Diamonds",
                            Value = 3
                        },
                        new
                        {
                            Id = new Guid("76a41734-5a6a-41ed-bef1-8c0ee34cdaa0"),
                            CardIMG = "",
                            DeckId = new Guid("e01c46df-21e8-4ea4-9697-731b428dee4a"),
                            Rank = "4",
                            Suit = "Diamonds",
                            Value = 4
                        },
                        new
                        {
                            Id = new Guid("e03f362d-b793-4a8d-b870-ac4c4bc2e766"),
                            CardIMG = "",
                            DeckId = new Guid("e01c46df-21e8-4ea4-9697-731b428dee4a"),
                            Rank = "5",
                            Suit = "Diamonds",
                            Value = 5
                        },
                        new
                        {
                            Id = new Guid("6789813c-9d29-493c-8b4d-78d4e9df14be"),
                            CardIMG = "",
                            DeckId = new Guid("e01c46df-21e8-4ea4-9697-731b428dee4a"),
                            Rank = "6",
                            Suit = "Diamonds",
                            Value = 6
                        },
                        new
                        {
                            Id = new Guid("da3e6e93-692d-4624-ade7-8200d449821c"),
                            CardIMG = "",
                            DeckId = new Guid("e01c46df-21e8-4ea4-9697-731b428dee4a"),
                            Rank = "7",
                            Suit = "Diamonds",
                            Value = 7
                        },
                        new
                        {
                            Id = new Guid("abe2ae18-7769-4a79-9760-f0ed5a1c7963"),
                            CardIMG = "",
                            DeckId = new Guid("e01c46df-21e8-4ea4-9697-731b428dee4a"),
                            Rank = "8",
                            Suit = "Diamonds",
                            Value = 8
                        },
                        new
                        {
                            Id = new Guid("92cea1e9-8aaa-4feb-8422-0751eb71e35b"),
                            CardIMG = "",
                            DeckId = new Guid("e01c46df-21e8-4ea4-9697-731b428dee4a"),
                            Rank = "9",
                            Suit = "Diamonds",
                            Value = 9
                        },
                        new
                        {
                            Id = new Guid("02000ff8-5b1e-4989-9384-826f1e0c6c3a"),
                            CardIMG = "",
                            DeckId = new Guid("e01c46df-21e8-4ea4-9697-731b428dee4a"),
                            Rank = "10",
                            Suit = "Diamonds",
                            Value = 10
                        },
                        new
                        {
                            Id = new Guid("08a281de-b031-4600-b94f-9abd93162861"),
                            CardIMG = "",
                            DeckId = new Guid("e01c46df-21e8-4ea4-9697-731b428dee4a"),
                            Rank = "Jack",
                            Suit = "Diamonds",
                            Value = 10
                        },
                        new
                        {
                            Id = new Guid("f79078f3-e449-4b94-a5e2-dbc7dec90ebb"),
                            CardIMG = "",
                            DeckId = new Guid("e01c46df-21e8-4ea4-9697-731b428dee4a"),
                            Rank = "Queen",
                            Suit = "Diamonds",
                            Value = 10
                        },
                        new
                        {
                            Id = new Guid("62ad26ca-ba8d-4698-a70e-77fc484944f0"),
                            CardIMG = "",
                            DeckId = new Guid("e01c46df-21e8-4ea4-9697-731b428dee4a"),
                            Rank = "King",
                            Suit = "Diamonds",
                            Value = 10
                        },
                        new
                        {
                            Id = new Guid("4b17d9fa-151f-4ddc-8381-2a28d834cbb7"),
                            CardIMG = "",
                            DeckId = new Guid("e01c46df-21e8-4ea4-9697-731b428dee4a"),
                            Rank = "Ace",
                            Suit = "Clubs",
                            Value = 1
                        },
                        new
                        {
                            Id = new Guid("af4fdae0-54c6-4735-8a1c-f5ceb89e5016"),
                            CardIMG = "",
                            DeckId = new Guid("e01c46df-21e8-4ea4-9697-731b428dee4a"),
                            Rank = "2",
                            Suit = "Clubs",
                            Value = 2
                        },
                        new
                        {
                            Id = new Guid("da05d94e-833d-4b4a-a52c-57309ad4cf03"),
                            CardIMG = "",
                            DeckId = new Guid("e01c46df-21e8-4ea4-9697-731b428dee4a"),
                            Rank = "3",
                            Suit = "Clubs",
                            Value = 3
                        },
                        new
                        {
                            Id = new Guid("d14f5c3f-3bfe-4a1f-94b2-bb678a1717c5"),
                            CardIMG = "",
                            DeckId = new Guid("e01c46df-21e8-4ea4-9697-731b428dee4a"),
                            Rank = "4",
                            Suit = "Clubs",
                            Value = 4
                        },
                        new
                        {
                            Id = new Guid("349cbb4c-1fb8-4f4c-a12d-a342de1c34b3"),
                            CardIMG = "",
                            DeckId = new Guid("e01c46df-21e8-4ea4-9697-731b428dee4a"),
                            Rank = "5",
                            Suit = "Clubs",
                            Value = 5
                        },
                        new
                        {
                            Id = new Guid("53c9e3ac-046a-476c-8de8-18d6f2a83d3a"),
                            CardIMG = "",
                            DeckId = new Guid("e01c46df-21e8-4ea4-9697-731b428dee4a"),
                            Rank = "6",
                            Suit = "Clubs",
                            Value = 6
                        },
                        new
                        {
                            Id = new Guid("d6923f35-f627-4c44-97f9-7e29d993ad19"),
                            CardIMG = "",
                            DeckId = new Guid("e01c46df-21e8-4ea4-9697-731b428dee4a"),
                            Rank = "7",
                            Suit = "Clubs",
                            Value = 7
                        },
                        new
                        {
                            Id = new Guid("1f23c4c2-3d52-437a-ab46-11637f5f28c9"),
                            CardIMG = "",
                            DeckId = new Guid("e01c46df-21e8-4ea4-9697-731b428dee4a"),
                            Rank = "8",
                            Suit = "Clubs",
                            Value = 8
                        },
                        new
                        {
                            Id = new Guid("cb3d9ce6-874d-4085-83ab-48a1952bbf9f"),
                            CardIMG = "",
                            DeckId = new Guid("e01c46df-21e8-4ea4-9697-731b428dee4a"),
                            Rank = "9",
                            Suit = "Clubs",
                            Value = 9
                        },
                        new
                        {
                            Id = new Guid("15b9df11-5be1-4f72-8a0f-a7250899a3f8"),
                            CardIMG = "",
                            DeckId = new Guid("e01c46df-21e8-4ea4-9697-731b428dee4a"),
                            Rank = "10",
                            Suit = "Clubs",
                            Value = 10
                        },
                        new
                        {
                            Id = new Guid("679044d2-de9b-4360-86fb-f4fce44d7281"),
                            CardIMG = "",
                            DeckId = new Guid("e01c46df-21e8-4ea4-9697-731b428dee4a"),
                            Rank = "Jack",
                            Suit = "Clubs",
                            Value = 10
                        },
                        new
                        {
                            Id = new Guid("2da03c0e-86d2-49ba-9b58-0a71f2a1d5ed"),
                            CardIMG = "",
                            DeckId = new Guid("e01c46df-21e8-4ea4-9697-731b428dee4a"),
                            Rank = "Queen",
                            Suit = "Clubs",
                            Value = 10
                        },
                        new
                        {
                            Id = new Guid("76bbd0de-7a0e-4d5f-b0d5-4558d13342f5"),
                            CardIMG = "",
                            DeckId = new Guid("e01c46df-21e8-4ea4-9697-731b428dee4a"),
                            Rank = "King",
                            Suit = "Clubs",
                            Value = 10
                        });
                });

            modelBuilder.Entity("BlackJack.PL.Entities.tblDeck", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("tblDecks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e01c46df-21e8-4ea4-9697-731b428dee4a"),
                            GameId = new Guid("ae68511d-e1e3-4ebc-832d-9b2878d9854b")
                        },
                        new
                        {
                            Id = new Guid("2d25ded1-dbd0-4a19-bf73-76fa858a850b"),
                            GameId = new Guid("7b36ee30-6610-41d9-ada0-4d1754902f96")
                        },
                        new
                        {
                            Id = new Guid("86b0cf81-ff6f-4303-a633-062f104fe124"),
                            GameId = new Guid("0394e928-e4a5-4259-8966-22e5ceec478c")
                        });
                });

            modelBuilder.Entity("BlackJack.PL.Entities.tblGame", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("tblGames");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ae68511d-e1e3-4ebc-832d-9b2878d9854b"),
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("7b36ee30-6610-41d9-ada0-4d1754902f96"),
                            Status = false
                        },
                        new
                        {
                            Id = new Guid("0394e928-e4a5-4259-8966-22e5ceec478c"),
                            Status = true
                        });
                });

            modelBuilder.Entity("BlackJack.PL.Entities.tblPlayerHand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("tblUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("tblUserId");

                    b.ToTable("tblPlayerHands");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e3543e43-5c46-4f3f-8dca-ca36c2a10ec0"),
                            CardId = new Guid("588aacd0-92f3-4526-9526-9e1a91fffed1"),
                            UserId = new Guid("d4ea645d-1a07-44ce-9345-e245e46a6f2f")
                        },
                        new
                        {
                            Id = new Guid("981f0ef7-3e06-4c7f-b70a-65495f17ef16"),
                            CardId = new Guid("1ab1a9cd-b681-4858-a0b1-2d650e7f12af"),
                            UserId = new Guid("d4ea645d-1a07-44ce-9345-e245e46a6f2f")
                        },
                        new
                        {
                            Id = new Guid("ab5e9d6b-2dde-408c-8ff8-ca3495145295"),
                            CardId = new Guid("1ab1a9cd-b681-4858-a0b1-2d650e7f12af"),
                            UserId = new Guid("609a2008-d017-485f-961d-7ef8d22c4695")
                        },
                        new
                        {
                            Id = new Guid("2b3f8e81-1dde-4d91-bd5d-45ba294e96d1"),
                            CardId = new Guid("7fcff96d-8ebb-4e88-99c9-99e1fe4d2eaa"),
                            UserId = new Guid("609a2008-d017-485f-961d-7ef8d22c4695")
                        });
                });

            modelBuilder.Entity("BlackJack.PL.Entities.tblUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsComputerPlayer")
                        .HasColumnType("bit");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Wins")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("tblUsers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d4ea645d-1a07-44ce-9345-e245e46a6f2f"),
                            GameId = new Guid("ae68511d-e1e3-4ebc-832d-9b2878d9854b"),
                            IsComputerPlayer = false,
                            Nickname = "Stef",
                            Password = "SerSsQZr2h4Sf2rgvRY3eNCFh+PpfZ7VjozJmXJGChw=",
                            Score = 12,
                            Username = "Stefan",
                            Wins = 37
                        },
                        new
                        {
                            Id = new Guid("609a2008-d017-485f-961d-7ef8d22c4695"),
                            GameId = new Guid("ae68511d-e1e3-4ebc-832d-9b2878d9854b"),
                            IsComputerPlayer = false,
                            Nickname = "Zach",
                            Password = "1TMdfaWrqALnYwE2LIDjXLBHAidQ+XZXxqZETIfbVwo=",
                            Score = 13,
                            Username = "Zachary",
                            Wins = 1
                        },
                        new
                        {
                            Id = new Guid("6dc680ae-366d-4316-9cc2-4ba1b2caca84"),
                            IsComputerPlayer = false,
                            Nickname = "Andy",
                            Password = "0DjJI+EtsxRM1PvfmpFRP6D9a6mraGmr0cEEK7vOQZ0=",
                            Score = 15,
                            Username = "Anthony",
                            Wins = 14
                        });
                });

            modelBuilder.Entity("BlackJack.PL.Entities.tblCard", b =>
                {
                    b.HasOne("BlackJack.PL.Entities.tblDeck", "Deck")
                        .WithMany("tblCards")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deck");
                });

            modelBuilder.Entity("BlackJack.PL.Entities.tblDeck", b =>
                {
                    b.HasOne("BlackJack.PL.Entities.tblGame", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("BlackJack.PL.Entities.tblPlayerHand", b =>
                {
                    b.HasOne("BlackJack.PL.Entities.tblCard", "Card")
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlackJack.PL.Entities.tblUser", null)
                        .WithMany("tblPlayerHands")
                        .HasForeignKey("tblUserId");

                    b.Navigation("Card");
                });

            modelBuilder.Entity("BlackJack.PL.Entities.tblUser", b =>
                {
                    b.HasOne("BlackJack.PL.Entities.tblGame", "Game")
                        .WithMany("tblUsers")
                        .HasForeignKey("GameId");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("BlackJack.PL.Entities.tblDeck", b =>
                {
                    b.Navigation("tblCards");
                });

            modelBuilder.Entity("BlackJack.PL.Entities.tblGame", b =>
                {
                    b.Navigation("tblUsers");
                });

            modelBuilder.Entity("BlackJack.PL.Entities.tblUser", b =>
                {
                    b.Navigation("tblPlayerHands");
                });
#pragma warning restore 612, 618
        }
    }
}
